//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAR_CENTERE_entities : DbContext
    {
        public CAR_CENTERE_entities()
            : base("name=CAR_CENTERE_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLN_CLIENTE> CLN_CLIENTE { get; set; }
        public DbSet<CTG_CATALOGO> CTG_CATALOGO { get; set; }
        public DbSet<DTL_DETALLE_MANTENIMIENTO_RPT> DTL_DETALLE_MANTENIMIENTO_RPT { get; set; }
        public DbSet<DTL_DETALLE_MANTENIMIENTO_SRV> DTL_DETALLE_MANTENIMIENTO_SRV { get; set; }
        public DbSet<EMP_EMPLEADO> EMP_EMPLEADO { get; set; }
        public DbSet<FAC_FACTURA> FAC_FACTURA { get; set; }
        public DbSet<MTN_MANTENIMIENTO> MTN_MANTENIMIENTO { get; set; }
        public DbSet<RPT_REPUESTO> RPT_REPUESTO { get; set; }
        public DbSet<SRV_SERVICIO> SRV_SERVICIO { get; set; }
        public DbSet<TDN_TIENDA> TDN_TIENDA { get; set; }
        public DbSet<VHE_VEHICULO> VHE_VEHICULO { get; set; }
        public DbSet<VLC_VALOR_CATALOGO> VLC_VALOR_CATALOGO { get; set; }
        public DbSet<DTL_DETALLE_FACTURA_RPT> DTL_DETALLE_FACTURA_RPT { get; set; }
        public DbSet<DTL_DETALLE_FACTURA_SRV> DTL_DETALLE_FACTURA_SRV { get; set; }
    }
}
