//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLN_CLIENTE
    {
        public CLN_CLIENTE()
        {
            this.VHE_VEHICULO = new HashSet<VHE_VEHICULO>();
        }
    
        public int CLN_ID { get; set; }
        public Nullable<int> CLN_TIPO_DOCUMENTO { get; set; }
        public string CLN_NUMERO_DOCUMENTO { get; set; }
        public string CLN_PRIMER_NOMBRE { get; set; }
        public string CLN_SEGUNDO_NOMBRE { get; set; }
        public string CLN_PRIMER_APELLIDO { get; set; }
        public string CLN_SEGUNDO_APELLIDO { get; set; }
        public decimal CLN_CELULAR { get; set; }
        public string CLN_DIRECCION { get; set; }
        public string CLN_EMAIL { get; set; }
        public Nullable<int> CLN_ESTADO { get; set; }
    
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO1 { get; set; }
        public virtual ICollection<VHE_VEHICULO> VHE_VEHICULO { get; set; }
    }
}
