//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTL_DETALLE_FACTURA_SRV
    {
        public Nullable<int> DTL_ID_FACTURA { get; set; }
        public int DTL_DETALLE_SRV { get; set; }
        public Nullable<decimal> DTL_DESCUENTO_SRV { get; set; }
        public decimal DTL_VALOR { get; set; }
    
        public virtual FAC_FACTURA FAC_FACTURA { get; set; }
    }
}
