//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTL_DETALLE_MANTENIMIENTO_RPT
    {
        public int DTL_ID { get; set; }
        public Nullable<int> DTL_ID_MTN { get; set; }
        public string DTL_ID_REPUESTO { get; set; }
        public int DTL_CANTIDAD_RPT { get; set; }
        public Nullable<int> DTL_ESTADO { get; set; }
    
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO { get; set; }
        public virtual MTN_MANTENIMIENTO MTN_MANTENIMIENTO { get; set; }
        public virtual RPT_REPUESTO RPT_REPUESTO { get; set; }
    }
}
