//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EMPLEADO
    {
        public EMP_EMPLEADO()
        {
            this.DTL_DETALLE_MANTENIMIENTO_SRV = new HashSet<DTL_DETALLE_MANTENIMIENTO_SRV>();
            this.MTN_MANTENIMIENTO = new HashSet<MTN_MANTENIMIENTO>();
        }
    
        public int EMP_ID { get; set; }
        public Nullable<int> EMP_TIPO_DOCUMENTO { get; set; }
        public string EMP_NUMERO_DOCUMENTO { get; set; }
        public string EMP_PRIMER_NOMBRE { get; set; }
        public string EMP_SEGUNDO_NOMBRE { get; set; }
        public string EMP_PRIMER_APELLIDO { get; set; }
        public string EMP_SEGUNDO_APELLIDO { get; set; }
        public decimal EMP_CELULAR { get; set; }
        public string EMP_DIRECCION { get; set; }
        public string EMP_EMAIL { get; set; }
        public Nullable<int> EMP_ESTADO { get; set; }
        public Nullable<int> EMP_ID_TIENDA { get; set; }
    
        public virtual ICollection<DTL_DETALLE_MANTENIMIENTO_SRV> DTL_DETALLE_MANTENIMIENTO_SRV { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO { get; set; }
        public virtual TDN_TIENDA TDN_TIENDA { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO1 { get; set; }
        public virtual ICollection<MTN_MANTENIMIENTO> MTN_MANTENIMIENTO { get; set; }
    }
}
