//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAC_FACTURA
    {
        public FAC_FACTURA()
        {
            this.DTL_DETALLE_FACTURA_RPT = new HashSet<DTL_DETALLE_FACTURA_RPT>();
            this.DTL_DETALLE_FACTURA_SRV = new HashSet<DTL_DETALLE_FACTURA_SRV>();
        }
    
        public int FAC_ID { get; set; }
        public Nullable<int> FAC_ID_TIENDA { get; set; }
        public System.DateTime FAC_FECHA_REGISTRO { get; set; }
        public Nullable<int> FAC_ID_MTN { get; set; }
        public Nullable<int> FAC_ESTADO { get; set; }
        public decimal FAC_SUBTOTAL { get; set; }
        public decimal FAC_IMPUESTO { get; set; }
        public decimal FAC_TOTAL { get; set; }
    
        public virtual ICollection<DTL_DETALLE_FACTURA_RPT> DTL_DETALLE_FACTURA_RPT { get; set; }
        public virtual ICollection<DTL_DETALLE_FACTURA_SRV> DTL_DETALLE_FACTURA_SRV { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO { get; set; }
        public virtual TDN_TIENDA TDN_TIENDA { get; set; }
        public virtual MTN_MANTENIMIENTO MTN_MANTENIMIENTO { get; set; }
    }
}
