//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTN_MANTENIMIENTO
    {
        public MTN_MANTENIMIENTO()
        {
            this.DTL_DETALLE_MANTENIMIENTO_RPT = new HashSet<DTL_DETALLE_MANTENIMIENTO_RPT>();
            this.DTL_DETALLE_MANTENIMIENTO_SRV = new HashSet<DTL_DETALLE_MANTENIMIENTO_SRV>();
            this.FAC_FACTURA = new HashSet<FAC_FACTURA>();
        }
    
        public int MTN_ID { get; set; }
        public System.DateTime MTN_FECHA_ENTRADA { get; set; }
        public System.DateTime MTN_FECHA_SALIDA { get; set; }
        public string MTN_VEHICULO { get; set; }
        public Nullable<decimal> MTN_PRESUPUESTO { get; set; }
        public Nullable<int> MTN_ESTADO { get; set; }
        public string MTN_TECNICO { get; set; }
    
        public virtual ICollection<DTL_DETALLE_MANTENIMIENTO_RPT> DTL_DETALLE_MANTENIMIENTO_RPT { get; set; }
        public virtual ICollection<DTL_DETALLE_MANTENIMIENTO_SRV> DTL_DETALLE_MANTENIMIENTO_SRV { get; set; }
        public virtual EMP_EMPLEADO EMP_EMPLEADO { get; set; }
        public virtual ICollection<FAC_FACTURA> FAC_FACTURA { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO { get; set; }
        public virtual VHE_VEHICULO VHE_VEHICULO { get; set; }
    }
}
