//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_REPUESTO
    {
        public RPT_REPUESTO()
        {
            this.DTL_DETALLE_MANTENIMIENTO_RPT = new HashSet<DTL_DETALLE_MANTENIMIENTO_RPT>();
        }
    
        public int RPT_ID { get; set; }
        public string RPT_SERIAL { get; set; }
        public string RPT_NOMBRE { get; set; }
        public string RPT_DESCRIPCION { get; set; }
        public decimal RPT_PRECIO_UND { get; set; }
        public int RPT_UNIDADES { get; set; }
        public decimal RPT_PORC_DESCUENTO { get; set; }
    
        public virtual ICollection<DTL_DETALLE_MANTENIMIENTO_RPT> DTL_DETALLE_MANTENIMIENTO_RPT { get; set; }
    }
}
