//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_SERVICIO
    {
        public SRV_SERVICIO()
        {
            this.DTL_DETALLE_MANTENIMIENTO_SRV = new HashSet<DTL_DETALLE_MANTENIMIENTO_SRV>();
        }
    
        public int SRV_ID { get; set; }
        public string SRV_NOMBRE { get; set; }
        public string SRV_DESCRIPCION { get; set; }
        public decimal SRV_VALOR_MINIMO { get; set; }
        public decimal SRV_VALOR_MAXIMO { get; set; }
        public decimal SRV_DESCUENTO { get; set; }
    
        public virtual ICollection<DTL_DETALLE_MANTENIMIENTO_SRV> DTL_DETALLE_MANTENIMIENTO_SRV { get; set; }
    }
}
