//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDN_TIENDA
    {
        public TDN_TIENDA()
        {
            this.EMP_EMPLEADO = new HashSet<EMP_EMPLEADO>();
            this.FAC_FACTURA = new HashSet<FAC_FACTURA>();
        }
    
        public int TDN_ID { get; set; }
        public string TND_NOMBRE { get; set; }
        public string TND_DIRECCION { get; set; }
        public decimal TND_TELEFONO { get; set; }
        public Nullable<int> TND_ESTADO { get; set; }
    
        public virtual ICollection<EMP_EMPLEADO> EMP_EMPLEADO { get; set; }
        public virtual ICollection<FAC_FACTURA> FAC_FACTURA { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO { get; set; }
    }
}
