//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VHE_VEHICULO
    {
        public VHE_VEHICULO()
        {
            this.MTN_MANTENIMIENTO = new HashSet<MTN_MANTENIMIENTO>();
        }
    
        public int VHE_ID { get; set; }
        public string VHE_PLACA { get; set; }
        public string VHE_SERIAL_CHASIS { get; set; }
        public string VHE_SERIAL_MOTOR { get; set; }
        public Nullable<int> VHE_MARCA { get; set; }
        public Nullable<int> VHE_MODELO { get; set; }
        public Nullable<int> VHE_ESTADO_FISICO { get; set; }
        public string VHE_DESCRIPCION_ESTADO { get; set; }
        public Nullable<int> VHE_ESTADO { get; set; }
        public string VHE_PROPIETARIO { get; set; }
    
        public virtual CLN_CLIENTE CLN_CLIENTE { get; set; }
        public virtual ICollection<MTN_MANTENIMIENTO> MTN_MANTENIMIENTO { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO1 { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO2 { get; set; }
        public virtual VLC_VALOR_CATALOGO VLC_VALOR_CATALOGO3 { get; set; }
    }
}
