//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLC_VALOR_CATALOGO
    {
        public VLC_VALOR_CATALOGO()
        {
            this.CLN_CLIENTE = new HashSet<CLN_CLIENTE>();
            this.CLN_CLIENTE1 = new HashSet<CLN_CLIENTE>();
            this.DTL_DETALLE_MANTENIMIENTO_RPT = new HashSet<DTL_DETALLE_MANTENIMIENTO_RPT>();
            this.DTL_DETALLE_MANTENIMIENTO_SRV = new HashSet<DTL_DETALLE_MANTENIMIENTO_SRV>();
            this.EMP_EMPLEADO = new HashSet<EMP_EMPLEADO>();
            this.EMP_EMPLEADO1 = new HashSet<EMP_EMPLEADO>();
            this.FAC_FACTURA = new HashSet<FAC_FACTURA>();
            this.MTN_MANTENIMIENTO = new HashSet<MTN_MANTENIMIENTO>();
            this.TDN_TIENDA = new HashSet<TDN_TIENDA>();
            this.VHE_VEHICULO = new HashSet<VHE_VEHICULO>();
            this.VHE_VEHICULO1 = new HashSet<VHE_VEHICULO>();
            this.VHE_VEHICULO2 = new HashSet<VHE_VEHICULO>();
            this.VHE_VEHICULO3 = new HashSet<VHE_VEHICULO>();
        }
    
        public int VLC_ID { get; set; }
        public string VLC_DESCRIPCION { get; set; }
        public string VLC_VALOR { get; set; }
        public Nullable<int> CTG_ID { get; set; }
    
        public virtual ICollection<CLN_CLIENTE> CLN_CLIENTE { get; set; }
        public virtual ICollection<CLN_CLIENTE> CLN_CLIENTE1 { get; set; }
        public virtual CTG_CATALOGO CTG_CATALOGO { get; set; }
        public virtual ICollection<DTL_DETALLE_MANTENIMIENTO_RPT> DTL_DETALLE_MANTENIMIENTO_RPT { get; set; }
        public virtual ICollection<DTL_DETALLE_MANTENIMIENTO_SRV> DTL_DETALLE_MANTENIMIENTO_SRV { get; set; }
        public virtual ICollection<EMP_EMPLEADO> EMP_EMPLEADO { get; set; }
        public virtual ICollection<EMP_EMPLEADO> EMP_EMPLEADO1 { get; set; }
        public virtual ICollection<FAC_FACTURA> FAC_FACTURA { get; set; }
        public virtual ICollection<MTN_MANTENIMIENTO> MTN_MANTENIMIENTO { get; set; }
        public virtual ICollection<TDN_TIENDA> TDN_TIENDA { get; set; }
        public virtual ICollection<VHE_VEHICULO> VHE_VEHICULO { get; set; }
        public virtual ICollection<VHE_VEHICULO> VHE_VEHICULO1 { get; set; }
        public virtual ICollection<VHE_VEHICULO> VHE_VEHICULO2 { get; set; }
        public virtual ICollection<VHE_VEHICULO> VHE_VEHICULO3 { get; set; }
    }
}
